package app;

import javax.swing.ButtonModel;
import javax.swing.DefaultListModel;
import lib.LibP10;

public class form extends javax.swing.JFrame {

    String cMerchV, depMerchV, pMerchV, qMerchV, desMerchV;
    ButtonModel isrRaBtn;
    LibP10 myLib = new LibP10();
    DefaultListModel model = new DefaultListModel();

    /**
     * Creates new form form
     */
    public form() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        isrGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        depList = new javax.swing.JList<>();
        labelCMerch = new javax.swing.JLabel();
        labelDepartament = new javax.swing.JLabel();
        labelPrice = new javax.swing.JLabel();
        labelQuant = new javax.swing.JLabel();
        labelDiscount = new javax.swing.JLabel();
        codeMerch = new javax.swing.JTextField();
        priceMerch = new javax.swing.JTextField();
        quantMerch = new javax.swing.JTextField();
        descMerch = new javax.swing.JTextField();
        isr8 = new javax.swing.JRadioButton();
        isr16 = new javax.swing.JRadioButton();
        isrNull = new javax.swing.JRadioButton();
        labelSubTotal = new javax.swing.JLabel();
        subTotalOut = new javax.swing.JLabel();
        labelTotalMerch = new javax.swing.JLabel();
        totalMerch = new javax.swing.JLabel();
        btnCotizar = new javax.swing.JButton();
        btnClsMerch = new javax.swing.JButton();
        btnAddtoCart = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        cart = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        buyCart = new javax.swing.JButton();
        btnClsCart = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cartTotal = new javax.swing.JLabel();
        removeItemCart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        depList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Hombre", "Mujer", "Hogar", "Perfumeria", "Zapateria" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(depList);

        labelCMerch.setText("Codigo de Mercancia");

        labelDepartament.setText("Departamento");

        labelPrice.setText("Precio");

        labelQuant.setText("Cantidad");

        labelDiscount.setText("Descuento %");

        codeMerch.setPreferredSize(new java.awt.Dimension(100, 25));

        priceMerch.setPreferredSize(new java.awt.Dimension(80, 25));

        quantMerch.setPreferredSize(new java.awt.Dimension(80, 25));

        descMerch.setPreferredSize(new java.awt.Dimension(80, 25));

        isrGroup.add(isr8);
        isr8.setText("8% ISR");
        isr8.setActionCommand("8ISR");
        isr8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isr8ActionPerformed(evt);
            }
        });

        isrGroup.add(isr16);
        isr16.setText("16% ISR");
        isr16.setActionCommand("16ISR");

        isrGroup.add(isrNull);
        isrNull.setText("Sin ISR");
        isrNull.setActionCommand("nullISR");

        labelSubTotal.setText("SubTotal");

        subTotalOut.setText("..");

        labelTotalMerch.setText("Total");

        totalMerch.setText("..");

        btnCotizar.setText("Cotizar");
        btnCotizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCotizarActionPerformed(evt);
            }
        });

        btnClsMerch.setText("Limpiar");
        btnClsMerch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClsMerchActionPerformed(evt);
            }
        });

        btnAddtoCart.setText("Add");
        btnAddtoCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtoCartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelTotalMerch)
                        .addGap(33, 33, 33)
                        .addComponent(totalMerch, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(btnCotizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClsMerch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddtoCart, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelDepartament)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(isr16)
                                            .addComponent(isr8)
                                            .addComponent(isrNull)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(labelQuant)
                                                    .addComponent(labelPrice))
                                                .addGap(33, 33, 33)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(quantMerch, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                                    .addComponent(priceMerch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(labelDiscount)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(descMerch, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelCMerch)
                                        .addGap(18, 18, 18)
                                        .addComponent(codeMerch, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelSubTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(subTotalOut, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCMerch)
                    .addComponent(codeMerch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelDepartament)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPrice)
                            .addComponent(priceMerch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelQuant)
                            .addComponent(quantMerch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descMerch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDiscount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isr8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isr16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isrNull)))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSubTotal)
                    .addComponent(subTotalOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalMerch)
                    .addComponent(btnCotizar)
                    .addComponent(btnClsMerch)
                    .addComponent(btnAddtoCart)
                    .addComponent(totalMerch))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        jScrollPane4.setViewportView(cart);

        jLabel2.setText("Carrito");

        buyCart.setText("Comprar");
        buyCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyCartActionPerformed(evt);
            }
        });

        btnClsCart.setText("Vaciar");
        btnClsCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClsCartActionPerformed(evt);
            }
        });

        jButton6.setText("Finalizar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel5.setText("TotalCarito:");

        cartTotal.setText("...");

        removeItemCart.setText("Remover");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnClsCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buyCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(7, 7, 7)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(removeItemCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cartTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buyCart)
                    .addComponent(removeItemCart))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClsCart)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cartTotal))
                .addGap(45, 45, 45))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isr8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isr8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isr8ActionPerformed

    private void btnClsCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClsCartActionPerformed

        // BOTON LIMPIEZA CARRITO
        model.removeAllElements();
        myLib.clsCart();
        cartTotal.setText("");
    }//GEN-LAST:event_btnClsCartActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnCotizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCotizarActionPerformed
        cMerchV = codeMerch.getText();
        depMerchV = depList.getSelectedValue();
        pMerchV = priceMerch.getText();
        qMerchV = quantMerch.getText();
        isrRaBtn = isrGroup.getSelection(); // ModelButton
        desMerchV = descMerch.getText();

        if (myLib.getProductoIn(cMerchV, depMerchV, pMerchV, qMerchV, isrRaBtn, desMerchV) == true) {
            subTotalOut.setText(myLib.getSubTotal());
            totalMerch.setText(myLib.getTotal());
        }
    }//GEN-LAST:event_btnCotizarActionPerformed

    private void btnClsMerchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClsMerchActionPerformed
        // BOTON DE LIMPIEZA FROMULARIO        
        codeMerch.setText("");
        priceMerch.setText("");
        quantMerch.setText("");
        descMerch.setText("");
        depList.clearSelection();
        isrGroup.clearSelection();
        subTotalOut.setText("..");
        totalMerch.setText("..");
        myLib.clsProductoIn();
    }//GEN-LAST:event_btnClsMerchActionPerformed

    private void btnAddtoCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtoCartActionPerformed
        // BOTON AÑADIR AL CARRITO
        cart.setModel(model);
        if (myLib.validProduct()) {
            model.addElement(myLib.getCartItemAdded());
        }
    }//GEN-LAST:event_btnAddtoCartActionPerformed

    private void buyCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyCartActionPerformed
        // COMPRAR EL CARRITO
        System.out.println(myLib.getCartTotal());
        cartTotal.setText(myLib.getCartTotal());
    }//GEN-LAST:event_buyCartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddtoCart;
    private javax.swing.JButton btnClsCart;
    private javax.swing.JButton btnClsMerch;
    private javax.swing.JButton btnCotizar;
    private javax.swing.JButton buyCart;
    private javax.swing.JList<String> cart;
    private javax.swing.JLabel cartTotal;
    private javax.swing.JTextField codeMerch;
    private javax.swing.JList<String> depList;
    private javax.swing.JTextField descMerch;
    private javax.swing.JRadioButton isr16;
    private javax.swing.JRadioButton isr8;
    private javax.swing.ButtonGroup isrGroup;
    private javax.swing.JRadioButton isrNull;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelCMerch;
    private javax.swing.JLabel labelDepartament;
    private javax.swing.JLabel labelDiscount;
    private javax.swing.JLabel labelPrice;
    private javax.swing.JLabel labelQuant;
    private javax.swing.JLabel labelSubTotal;
    private javax.swing.JLabel labelTotalMerch;
    private javax.swing.JTextField priceMerch;
    private javax.swing.JTextField quantMerch;
    private javax.swing.JButton removeItemCart;
    private javax.swing.JLabel subTotalOut;
    private javax.swing.JLabel totalMerch;
    // End of variables declaration//GEN-END:variables
}
