/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Libreria_Estacionamiento.Clase_Libreria_Estacionamiento;
/**
 *
 * @author nombte estudiante
 */

import Libreria_Estacionamiento.Clase_Libreria_Estacionamiento;

public class JFrameEstacionamiento extends javax.swing.JFrame {

    /**
     * Creates new form JFrameEstacionamiento
     */
    public JFrameEstacionamiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputHoras = new javax.swing.JTextField();
        calcBtn = new javax.swing.JButton();
        clsBtn = new javax.swing.JButton();
        endBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        jLabel_Imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Cobro de estacionamiento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Cantidad de horas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        inputHoras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inputHoras.setText("0");
        getContentPane().add(inputHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 140, -1));

        calcBtn.setText("Importe de cobro");
        calcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcBtnActionPerformed(evt);
            }
        });
        getContentPane().add(calcBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        clsBtn.setText("Limpiar");
        clsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        endBtn.setText("Terminar");
        endBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endBtnActionPerformed(evt);
            }
        });
        getContentPane().add(endBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 255));
        jLabel3.setText("El importe a cobrar es");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        resultLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resultLabel.setForeground(new java.awt.Color(51, 0, 255));
        resultLabel.setText("????");
        getContentPane().add(resultLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 100, -1));

        jLabel_Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Formularios/Estacionamiento.jpeg"))); // NOI18N
        getContentPane().add(jLabel_Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 250, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcBtnActionPerformed

        Clase_Libreria_Estacionamiento libBib = new Clase_Libreria_Estacionamiento();
        
        String costo = libBib.calCostoEstaci(Integer.parseInt(inputHoras.getText()));
        
        resultLabel.setText(costo);
        
//         Clase_Libreria_Estacionamiento objeto_1 = new Clase_Libreria_Estacionamiento();
//         
//         resultLabel.setText(String.valueOf(objeto_1.funcion_cobro(Double.valueOf(inputHoras.getText()))));
//         


    }//GEN-LAST:event_calcBtnActionPerformed

    private void clsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clsBtnActionPerformed
        inputHoras.setText("0");
        resultLabel.setText("???");
        // TODO add your handling code here:
    }//GEN-LAST:event_clsBtnActionPerformed

    private void endBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endBtnActionPerformed
    System.exit(0);
            // TODO add your handling code here:
    }//GEN-LAST:event_endBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEstacionamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEstacionamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEstacionamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEstacionamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEstacionamiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcBtn;
    private javax.swing.JButton clsBtn;
    private javax.swing.JButton endBtn;
    private javax.swing.JTextField inputHoras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Imagen;
    private javax.swing.JLabel resultLabel;
    // End of variables declaration//GEN-END:variables
}
